config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/signup', to: 'users#new'

  resources :users do
    member do
      get :following, :followers
    end
  end

  root 'users#homefeed'
  resources :posts, only: [:create, :destroy]
  get '/login', to: 'sessions#new'
  resources :sessions, only: :create
  delete '/logout', to: 'sessions#destroy'
  resources :relationships, only:[:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates :content, presence: true
	has_one_attached :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence:true
	validates :followed_id, presence:true
end

app/models/user.rb
class User < ApplicationRecord
	#This is basic validation
	validates :name, presence: true, length: { maximum:50 }
	#To validate correct email structure
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum:50 },
																		format: { with: EMAIL_REGEX },
																		uniqueness: { case_sensitive: false}
	has_secure_password #Equivalent of password and password confirmation
	validates :password, presence: true, length: { minimum: 6 }, allow_nil:true #It shoud be place after "has_secured_password since it is depending on Bcrypt"
	has_many :posts

	has_many :active_relationships, class_name: "Relationship", foreign_key:"follower_id",  dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship", foreign_key:"followed_id", dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower

	#follow auser
	def follow(other_user)
		active_relationships.create(followed_id: other_user.id)
	end

	#unfollow user
	def unfollow(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end

	def following?(other_user)
		Relationship.find_by_followed_id(other_user.id)
	end

	#will handle or to fetch followings posts/Return user feeds
	def feed
		Post.where("user_id IN (?) OR user_id = ?", following.ids, id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper

	def logged_in_user  
		unless logged_in?  #if not login
			flash[:danger] = "Please login first"
			redirect_to login_url
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def  home
	  #condition check if user is logged in, if login render "users/homefeed"
	  #homefeed=>Add homefeed.html.erb in Users Views, no need to put else
	  if logged_in?
			@post = current_user.posts.build
			@posts = current_user.feed.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
			# @posts = current_user.posts.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
			render "users/homefeed"
	  end
	end

	def  about
		
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Successfully Created!"
		else
			flash[:danger] = "Please input content"
		end
		redirect_back(fallback_location: request.referer)
	end

	def destroy
		@post = Post.find(params[:id])
    	@post.destroy
		redirect_back(fallback_location: request.referer)
	end

	private
		def post_params
			params.require(:post).permit(:content, :image)
		end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	#when follow a user
	def create
		@user = User.find(params[:followed_id])
		current_user.follow(@user)
		flash[:success] = "Successfully followed #{@user.name}"
		redirect_back(fallback_location: request.referer)
	end

	def destroy
		user = Relationship.find(params[:id]).followed
		current_user.unfollow(user)
		flash[:success] = "Successfully unfollowed #{user.name}"
		redirect_back(fallback_location: request.referer)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			#login user
			log_in(user)
			flash[:success] = "Successfully Created"
			redirect_to root_url
		else
			#redirect back to the login page
			flash[:danger] = "Invalid Credentials"
			redirect_to login_url
		end
	end

	def destroy
		log_out
		flash[:success] = "Successfully Logout"
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, except: [:new, :create]
	before_action :correct_user, only: [:edit, :update]

	def index
		@users = User.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Successfully Created a account."
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "Successfully Updated Profile."
			redirect_to root_url
		else
			render 'edit'
		end
  end
	
	def show
		@user = User.find(params[:id])
		@posts = @user.posts.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
	end

	def following
		@user = User.find(params[:id])
		@users = @user.following.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
	end

	def followers
		@user = User.find(params[:id])
		@users = @user.followers.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def correct_user
			user = User.find(params[:id])
			if user != current_user
				flash[:danger] = "You are not authorized"
				redirect_to root_url
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:userid] = user.id
	end

	def log_out
		session.delete(:userid)
	end

	def current_user
		User.find_by(id: session[:userid])
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def profile_image(user, size)
		#generate the hex token
		gravatar_id = Digest::MD5::hexdigest(user.email)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class:"rounded-circle #{size}")
	end
end

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
    <% flash.each do |type,msg| %>
    <div class="mt-4 alert alert-<%= type%> alert-dismissible fade show" role="alert">
        <strong><%= msg%></strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <%end%>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
<div class="container">
    <a class="navbar-brand" href="#">The Bro</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="ml-auto navbar-nav">
            <li class="nav-item">
                <%= link_to "Home", root_path, class:"nav-link" %>
            </li>
             <li class="nav-item">
                 <%= link_to "About", about_path, class:"nav-link" %>
            </li>
            <%if logged_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         <%= profile_image(current_user, "profile-small")%>
                         <%= current_user.name %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to "Edit", edit_user_path(current_user),  class:"dropdown-item" %>
                        <%= link_to "Profile", user_path(current_user),  class:"dropdown-item" %>
                        <%= link_to "Users", users_path,  class:"dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Logout", logout_path, method: :delete, class:"dropdown-item" %>
                    </div>
                </li>
            <%else%>
                <li class="nav-item">
                    <%= link_to "Signup", signup_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Login", login_path, class:"nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container mt-4">
      <%= render 'layouts/flash_messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About")%>
<div class="container ">
    <div class="mt-5 row">
        <div class="col-6">
            <%= image_tag "rm.png", class: "img-fluid img1"%>
        </div>
        <div class=" col-6">
        <p>
            Hey, I’m Rey Mar. I am working at Office Partners 360 as a Web and Zoho Developer. 
            I also create projects or any applications regarding machine learning and Internet of Things(IOT).
        </p>
        <p>
            I learned hardware and software troubleshooting on my first internship at Cebu SmartBuild,
            an IT company in Cebu which specializes in networking products, FDAs and other technical
            process or solutions involving technology. After Cebu SmartBuild,
            I got my first shot in web development as web developer intern for almost 3 months
            at Getmore Philippines where I got a chance to work on Ruby-on-Rails and Ember.js,
            a web framework, and able to used bitbucket and github as a requirement for version control.
            I was hired by Office Partners 360 as a fulltime web developer and part of the admin team. 
            OP360 gives me an opportunity to explore, learn and integrate different technologies from 
            Low Code platform to web frameworks.
        </p>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<% provide(:title, "Home")%>
<div class="container jumbotron">
    <h1 class="display-4 ">The Bro's Twitter Clone</h1>
    <p>Welcome to my Site!</p>
</div>

app/views/posts/_form.html.erb
<div>
    <%= form_for @post do |f| %>
        <div class="form-group">
            <%= f.text_area :content, size:"20x5", class: "form-control", placeholder: "Share your thoughts..." %>
        </div>
        <div class="form-group">
            <%= f.file_field :image %>
        </div>
           <%= f.submit "Post", class: "btn btn-primary btn-block mt-2"%>
    <%end%>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?%>
    <div class="alert alert-danger">
    This form contains errors.
    </div>
    <ul>
        <%@user.errors.full_messages.each do |msg|%>
            <li><%=msg%></li>
        <%end%>
    </ul>
<%end%>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build do |f|%>
    <%= hidden_field_tag 'followed_id', @user.id%>
    <%= f.submit "Follow", class:"btn btn-primary"%>
<%end%>

app/views/users/_follow_form.html.erb
<%if current_user != @user %>
    <%if current_user.following?(@user)%>
        <%= render "Unfollow"%>
    <%else%>
        <%= render "follow"%>
    <%end%>
<%end%>

app/views/users/_form.html.erb
<div>
    <%= form_for @user do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>
        <div class="form-group">
            <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
        </div>
        <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
          <div class="form-group">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
        </div>
        <%= f.submit btn_msg, class: "btn btn-primary btn-block"%>
    <%end%>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
     html: {method: :delete} do |f|%>
     <%= f.submit "Unfollow", class: "btn btn-secondary"%>
<%end%>

app/views/users/_user.html.erb
 <div class="col-6">
    <div class="mb-3 card">
        <div class="card-body">
            <div class="col-2">
                <%= profile_image(user, "profile-big")%>
            </div>
            <div class="col-10">
                <h6><%= link_to user.name, user_path(user)%></h6>
                <span><%= user.email%></span>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<div class="row">
    <div class="col-6 mx-auto">
        <h1 class="text-center mt-4">Edit Profile</h1>
        <%= render "form", btn_msg: "Update Profile" %>
    </div>
</div>

app/views/users/followers.html.erb
<% provide(:title,"Followers")%>
<h1 class="mt-4 text-center">All Followers</h1>
 <div class="row">
    <!-- will auto find or render the _user.html.erb -->
    <%= render @users%> 
</div>

<div class="mt-4 pagination justify-content-center">
    <%= will_paginate @users%>
</div>

app/views/users/following.html.erb
<% provide(:title,"Following")%>
<h1 class="mt-4 text-center">All Following</h1>
 <div class="row">
    <!-- will auto find or render the _user.html.erb -->
    <%= render @users%> 
</div>

<div class="mt-4 pagination justify-content-center">
    <%= will_paginate @users%>
</div>

app/views/users/homefeed.html.erb
<% provide(:title, "Homefeed")%>
<div class="row">
	<div class="col-4">
		<div class="mt-4 mr-auto card">
			<div class="card-header">
				User Information
			</div>
			<div class="card-body">
				<div class="text-center">
					<%= profile_image(current_user, "profile-big")%>
				</div>
				<div class="mx-auto text-center">
					<h5 class="card-title"><%= current_user.name%></h5>
					<p class="card-text"> <%= current_user.email%></p>
				</div>
			</div>
            <div class="card-footer">
                <%= render "posts/form"%>
            </div>
		</div>
	</div>

    <div class="col-8">
		<div class="mt-4 ml-auto card">
			<div class="card-header">
				Activity Feeds
			</div>
				<% @posts.each do |u| %>
					<div class="mt-4 media p-lg-2">
						<%= profile_image(current_user, "profile-feed" )%>
						<div class="mt-2 ml-2 media-body">
							<h5><%= u.user.email%> </h5>
							<%= image_tag(u.image, style:'width:20%; height:auto')  if u.image.attached?%>
							<p><%= u.content%> </p>
							<small class="text-muted">Posted <%= time_ago_in_words(u.created_at)%> </small>
							<% if current_user == u.user %>
								<%= link_to post_path(u.id), method: :delete,
									data: {confirm:"Are you sure"},
									class: "float-right btn btn-outline-danger" do %>
									Delete
								<%end%>
							<%end%>
						</div>
					
					</div>
					<hr class="mt-2 mb-2"/>
				<%end%>
			</div>
			<div class="mt-4 pagination justify-content-center">
				<%= will_paginate @posts%>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title,"Users")%>
<h1 class="mt-4 text-center">All Users</h1>
 <div class="row">
    <!-- will auto find or render the _user.html.erb -->
    <%= render @users%> 
</div>

<div class="mt-4 pagination justify-content-center">
    <%= will_paginate @users%>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<div class="row">
    <div class="col-6 mx-auto">
        <h1 class="text-center mt-4">Sign up</h1>
        <%= render "form", btn_msg: "Create a new account" %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Show")%>
<div class="row">
	<div class="col-4">
		<div class="mt-4 mr-auto card">
			<div class="card-header">
				User Information
			</div>
			<div class="card-body">
				<div class="text-center">
					<%= profile_image(@user, "profile-big")%>
				</div>
				<div class="mx-auto text-center">
					<h5 class="card-title"><%= @user.name%></h5>
					<p class="card-text"> <%= @user.email%></p>
					<div class="row">
						<div class="col-6">
							<%= link_to "#{@user.following.count} followings", following_user_path(@user)%>
						</div>
						<div class="col-6">
							<%= link_to "#{@user.followers.count} followers",  followers_user_path(@user)%>
						</div>
					</div>
					<div class="mt-2"><%= render 'follow_form' %></div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-8">
		<div class="mt-4 ml-auto card">
			<div class="card-header">
				Activity Feeds
			</div>
				<% @posts.each do |u| %>
					<div class="mt-4 media p-lg-2">
						<%= profile_image(@user, "profile-big" )%>
						<div class="mt-2 ml-2 media-body">
							<h4><%= u.user.email%></h4>
							<p><%= u.content%> </p>
						</div>
						<%= link_to "Delete", post_path(u.id), method: :delete, class:"btn btn-danger", data: {confirm:"Are you sure you want to delete?"}%>
					</div>
				<%end%>
			</div>
			<div class="mt-4 pagination justify-content-center">
				<%= will_paginate @posts%>
			</div>
		</div>
	</div>
</div>